version: '3'

services:
  vn-lot-ai-dashboard:
    image: vn-lot-ai-dashboard:v0.0.1-alpha
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - shared_network

networks:
  shared_network:
    external: true
