import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import theme from '../theme';
import DatePickerWrapper from './components/forms/DatePickerWrapper';
import "./globals.css";
import { StoreProvider } from "./StoreProvider";
import SideNav from './components/navigation/SideNav';
const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={theme}>
              <div className='p-4'>
                <div className="flex flex-row w-full gap-1">
                  <div className='flex flex-row w-1/2 justify-start items-start'>
                    <SideNav />
                  </div>
                  <div className='flex flex-row w-1/2 justify-end items-center'>
                    <DatePickerWrapper />
                  </div>
                </div>
                <div className="flex flex-col items-center justify-center">
                  {children}
                </div>
              </div>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
