name: Build and Push Docker Image (on tag)

on:
  push:
    tags:
      - '*'  # Triggers on any tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vn-lot-ai-dashboard:${{ env.TAG }} .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vn-lot-ai-dashboard:${{ env.TAG }}
